### ISSUE TITLE
GitterからSlackへの移行を検討

### ISSUE THREAD

**Issue by uribo** [TokyoR/r-wakalang#3]
### やったこと
- [x] Slackにチームを作成
  - チーム名: Tokyo.R
  -  URL: https://r-wakalang.slack.com
- [x] [slackin](https://github.com/rauchg/slackin)の指示書き通り、slackチームへの参加ボタンとリンクの設置 <a href="https://r-wakalang.herokuapp.com"><img src="https://r-wakalang.herokuapp.com/badge.svg"></a> (ec801b5, 1af4799)
- [x] GitHubリポジトリ（ここ）との連携... pushしたりissuesに書き込みがあると`general`チャンネルに内容が書き込まれる（チャンネルや設定は変更可能）
- [x] Twitter上で告知 https://twitter.com/u_ribo/status/613719634202595328 移行を促進。
  - :warning: @teramonagiさんがメールで招待された方全員がご存知である可能性は低いです。再度直接招待した方が良い
### Slackの利点と欠点

個人的に思ったものです。
#### 利点
- チャンネルを細かく設定できる（トピックごとに話題を分けられるかも）
  - 初期からある２つのチャンネルはそれぞれ、`general`（全体に対する連絡・情報共有用）、`random`（雑談用）というように使い分けたほうが良さ気 ref) http://www.bunnyhop.jp/tips-20140630/
- 利用している企業が多いのか、検索時にいろいろな情報が引っかかる（興味のあるものは実装できる）
- 各種サービス（GitHub, Dropbox, IFTTT...）との連携が強力
  - **君だけの盆栽（bot）**が作れる
- @yutannihilation がいろいろしてくれそう https://twitter.com/yutannihilation/status/613725187322675202
#### 欠点
- 一見使いにくい（**slack わからんぐ現象が頻発**）
- メールアドレスを登録しないと閲覧・書き込みが不可
- 通知がうざい -> 設定で変更可能
- 設定やら管理がアレ

**Comment by teramonagi** [comment]
ありがとうございます！

> メールアドレスを登録しないと閲覧・書き込みが不可

これだけが問題ですが、Tokyo.RのMLに流すなりして展開し、R初心者の方を積極的にサポートしたいところです！なので、もう移行でいいんじゃないかなと。

**Comment by yutannihilation** [comment]
> @yutannihilation がいろいろしてくれそう

えっ

**Comment by teramonagi** [comment]
週末に移行アナウンス＆Gitter閉じしておきます～！
